use_frameworks!

platform :ios, '11.4'

target 'FilteringPhotoAlbum_Example' do
  pod 'FilteringPhotoAlbum', :path => '../'

  target 'FilteringPhotoAlbum_Tests' do
    inherit! :search_paths

    
  end
end
